### ISSUE TITLE
null filters issue

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-plugin-simplesearch#44]
In /user/config/plugins/simplesearch.yaml I set `filters: []` and I get different results from if I set `filters:` 

`filters:` appears to get correct results

`filters: []` usually produces no results, but sometimes seems to work with a filter setting I used earlier. Eg I set `filters: [ England ]` and it works, then change it to `filters: []` and I may get the same result.

**Comment by rhukster** [comment]
Ok, i've debugged this and here's the problem.  By having `filters: []` in your configuration, this is getting merged with the default configuration.  Because it's merged, the `[]` is doing nothing and you are still left with the default `category: blog` setting.

The way to clear this out and search all is to simply set `filters:` with nothing after.  This results in filters being null, which is tested and then returns all pages.

There's not much I can do about this as this is how Grav merges configuration at a low level.

**Comment by ThosG** [comment]
Thanks Andy. In that case the documentation needs changing (IMO). The Readme for v1.7.0 says
NOTE: If you want to search **ALL PAGES** just keep the `filters: []` section empty.

Better would be the words you just wrote:

NOTE: If you want to search **ALL PAGES** simply set filters: with nothing after. This results in filters being null, which is tested and then returns all pages.

I take it you wouldn’t want to have a wilcard system, eg ‘filters: *’.

Thomas

**Comment by flaviocopes** [comment]
Fixed the doc
