### ISSUE TITLE
category filter not working

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-simplesearch#48]
Hi guys,

When adding multiple categories in the admin interface the search is not working at all. return always 0 results.
When only 1 category is used, then search is functioning as it should.

Is this an issue with simplesearch or perhaps the beta status of Grav and Admin (using both of the latest betas).

**Comment by hjone72** [comment]
I have also found that using no categories in the filter breaks search.

**Comment by flaviocopes** [comment]
Tested a bit.

Multiple categories work fine to me. Make sure you set the filter combinator to "or".

No categories on the other hand is an issue, because the default is

```
filters:
  category:
    - blog
```

if you add no categories to your config, the value is not saved to the custom configuration (user/config/plugins/simplesearch.yaml), so the default applies (searching for `category: blog`).

Quick solution is to open that file and add a line such as

```
filters:
```

We should however change the default, but this could change the settings for anyone updating the plugin, so not sure how reasonable it is.

**Comment by Salvatos** [comment]
I'd like to add a note that if you save your plugin options again from the admin panel, your empty `filters:` will get removed and you will need to add it in again, so keep an eye out for that.

**Comment by flaviocopes** [comment]
@Salvatos can you test me this change? https://github.com/getgrav/grav-plugin-simplesearch/commit/8c56aefa5730f039dcab8e839ca598c5ecd779c5  

Adding "none@" in the category filter box should make it work

**Comment by Salvatos** [comment]
@flaviocopes Seems to be working fine on my test install; it did not get saved the first time, but maybe it was a caching issue or something?

I would suggest also mentioning that feature in the tooltip.

Thank you!

**Comment by flaviocopes** [comment]
Good idea, added the tooltip
