### ISSUE TITLE
Search Results & Header Search Box Issues

### ISSUE THREAD

**Issue by cd13sr** [getgrav/grav-plugin-simplesearch#49]
I placed a searched box, via {% include 'partials/simplesearch_searchbox.html.twig' %}, in my header template. If I'm on the /search page and try to search for a new query from the search box on the page, not in the header, it will use the value from the search box in the header instead.

Thanks!

**Comment by hunternet93** [comment]
The simplesearch_searchbox template creates an input field and then watches for events. Once it gets an event, it gets the input by querying for all elements with the attribute `[data-search-input]`, instead of getting the event's target element as one might expect.

I've created a PR for a change that fixes the issue (#52), as an interim fix you can create your own `partials/simplesearch_searchbox.html.twig` in your theme's templates with the contents of [this file](https://github.com/hunternet93/grav-plugin-simplesearch/blob/multiple-searchboxes/templates/partials/simplesearch_searchbox.html.twig).

**Comment by cd13sr** [comment]
Thanks!
